// SPDX-License-Identifier: AGPL-3.0-or-later

export const VOICE_MESSAGE_HOLD_TOOLTIP_DURATION_MS = 2000;
export const VOICE_MESSAGE_MIN_SEND_DURATION_MS = 500;
export const VOICE_MESSAGE_RECORDING_TICK_MS = 120;
export const VOICE_MESSAGE_WAVEFORM_BAR_COUNT = 24;
export const VOICE_MESSAGE_WAVEFORM_UPDATE_INTERVAL_MS = 70;
export const VOICE_MESSAGE_LOCK_DRAG_MIN_VERTICAL_DELTA_PX = 52;
export const VOICE_MESSAGE_LOCK_DRAG_MAX_HORIZONTAL_DELTA_PX = 96;
