port: 7880
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: true
keys:
  replace-with-api-key: replace-with-api-secret
turn:
  enabled: true
  udp_port: 3478
  relay_range_start: 30000
  relay_range_end: 30100
