# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: {{.Values.global.namespace}}
  labels: {{- include "fluxer.labels" . | nindent 4}}
data:
  nats.conf: |
    listen: 0.0.0.0:{{ .Values.nats.clientPort }}
    http: 0.0.0.0:{{ .Values.nats.monitorPort }}
    max_payload: {{ .Values.nats.maxPayload | default "64MB" }}
    max_pending: {{ .Values.nats.maxPending | default "128MB" }}
    max_connections: {{ .Values.nats.maxConnections | default 2048 }}

    cluster {
      name: fluxer-nats
      listen: 0.0.0.0:{{ .Values.nats.clusterPort }}

      routes = [
        {{- range $i := until (int .Values.nats.replicas) }}
        nats-route://nats-{{ $i }}.nats-headless.{{ $.Values.global.namespace }}.svc.cluster.local:{{ $.Values.nats.clusterPort }}
        {{- end }}
      ]
    }
