# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
kind: Service
metadata:
  name: valkey-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fluxer.labels" . | nindent 4 }}
    app.kubernetes.io/name: valkey
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: valkey
      port: {{ .Values.valkey.port }}
      targetPort: valkey
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "fluxer.labels" . | nindent 4 }}
    app.kubernetes.io/name: valkey
spec:
  type: ClusterIP
  ports:
    - name: valkey
      port: {{ .Values.valkey.port }}
      targetPort: valkey
  selector:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: {{ .Release.Name }}
